import { Product, Category, Testimonial, PricingTier, FAQItem, Stat, TrustBrand, Order, Seller } from '../types';

export const categories: Category[] = [
  { id: 'tropical', name: 'Tropical', emoji: '🌴', count: 24, color: 'bg-yellow-100 text-yellow-800' },
  { id: 'citrus', name: 'Citrus', emoji: '🍊', count: 18, color: 'bg-orange-100 text-orange-800' },
  { id: 'berries', name: 'Berries', emoji: '🍓', count: 15, color: 'bg-red-100 text-red-800' },
  { id: 'stone', name: 'Stone Fruits', emoji: '🍑', count: 12, color: 'bg-pink-100 text-pink-800' },
  { id: 'exotic', name: 'Exotic', emoji: '🥝', count: 9, color: 'bg-purple-100 text-purple-800' },
  { id: 'seasonal', name: 'Seasonal', emoji: '🍏', count: 21, color: 'bg-green-100 text-green-800' },
];

export const products: Product[] = [
  {
    id: 'p1',
    name: 'Alphonso Mangoes',
    category: 'tropical',
    price: 8.99,
    unit: 'per kg',
    image: '',
    emoji: '🍐',
    badge: 'Bestseller',
    inStock: true,
    rating: 4.9,
    reviews: 284,
    origin: 'Ratnagiri, India',
    description: 'The king of mangoes — ultra-sweet, saffron-yellow, and buttery smooth. Harvested at peak ripeness.',
    organic: true,
  },
  {
    id: 'p2',
    name: 'Dragon Fruit',
    category: 'exotic',
    price: 6.49,
    unit: 'per piece',
    image: '',
    emoji: '🌉',
    badge: 'New',
    inStock: true,
    rating: 4.7,
    reviews: 132,
    origin: 'Mekong Delta, Vietnam',
    description: 'Vibrant pink skin with creamy white flesh and tiny black seeds. Rich in antioxidants.',
    organic: false,
  },
  {
    id: 'p3',
    name: 'Organic Strawberries',
    category: 'berries',
    price: 4.99,
    unit: 'per 500g',
    image: '',
    emoji: '🍓',
    badge: 'Organic',
    inStock: true,
    rating: 4.8,
    reviews: 419,
    origin: 'Huelva, Spain',
    description: 'Sun-ripened, fragrant, and irresistibly sweet. Picked fresh and delivered within 24 hours.',
    organic: true,
  },
  {
    id: 'p4',
    name: 'Valencia Oranges',
    category: 'citrus',
    price: 3.49,
    unit: 'per kg',
    image: '',
    emoji: '🍊',
    badge: '',
    inStock: true,
    rating: 4.6,
    reviews: 207,
    origin: 'Valencia, Spain',
    description: 'Juicy, thin-skinned oranges perfect for fresh-squeezed juice. High in Vitamin C.',
    organic: false,
  },
  {
    id: 'p5',
    name: 'Yellow Watermelon',
    category: 'seasonal',
    price: 12.99,
    unit: 'per melon',
    image: '',
    emoji: '🍉',
    badge: 'Seasonal',
    inStock: true,
    rating: 4.5,
    reviews: 89,
    origin: 'Almeria, Spain',
    description: 'Rare yellow-fleshed watermelon with honey-sweet flavor and a crisp, refreshing bite.',
    organic: false,
  },
  {
    id: 'p6',
    name: 'White Peaches',
    category: 'stone',
    price: 5.99,
    unit: 'per kg',
    image: '',
    emoji: '🍑',
    badge: 'Limited',
    inStock: true,
    rating: 4.8,
    reviews: 156,
    origin: 'Provence, France',
    description: 'Delicate, low-acid peaches with floral aroma and silky, melt-in-mouth texture.',
    organic: true,
  },
  {
    id: 'p7',
    name: 'Passion Fruit',
    category: 'exotic',
    price: 2.99,
    unit: 'per piece',
    image: '',
    emoji: '🟣',
    badge: '',
    inStock: true,
    rating: 4.7,
    reviews: 98,
    origin: 'Cundinamarca, Colombia',
    description: 'Intensely aromatic with tart-sweet pulp full of edible seeds. A tropical powerhouse.',
    organic: false,
  },
  {
    id: 'p8',
    name: 'Blueberry Box',
    category: 'berries',
    price: 7.49,
    unit: 'per 400g',
    image: '',
    emoji: '🫐',
    badge: 'Top Rated',
    inStock: true,
    rating: 4.9,
    reviews: 341,
    origin: 'Patagonia, Chile',
    description: 'Plump, deep-blue berries with firm skin and a perfect sweet-tart balance. Superfood grade.',
    organic: true,
  },
  {
    id: 'p9',
    name: 'Hass Avocados',
    category: 'tropical',
    price: 4.29,
    unit: 'per 3 pack',
    image: '',
    emoji: '🥑',
    badge: '',
    inStock: true,
    rating: 4.7,
    reviews: 512,
    origin: 'Michoacan, Mexico',
    description: 'Creamy, buttery Hass avocados at the ideal ripeness window. Rich in healthy fats.',
    organic: false,
  },
  {
    id: 'p10',
    name: 'Coconuts',
    category: 'tropical',
    price: 3.99,
    unit: 'per piece',
    image: '',
    emoji: '🥥',
    badge: '',
    inStock: true,
    rating: 4.5,
    reviews: 74,
    origin: 'Koh Samui, Thailand',
    description: 'Young green coconuts full of refreshing, electrolyte-rich water and tender jelly meat.',
    organic: false,
  },
  {
    id: 'p11',
    name: 'Pomegranate',
    category: 'exotic',
    price: 5.49,
    unit: 'per piece',
    image: '',
    emoji: '🟥',
    badge: 'Antioxidant Rich',
    inStock: true,
    rating: 4.8,
    reviews: 165,
    origin: 'Kandahar, Afghanistan',
    description: 'Jewel-red arils bursting with sweet-tart juice. One of the most antioxidant-dense fruits.',
    organic: true,
  },
  {
    id: 'p12',
    name: 'Fuji Apples',
    category: 'seasonal',
    price: 4.49,
    unit: 'per kg',
    image: '',
    emoji: '🍎',
    badge: '',
    inStock: true,
    rating: 4.6,
    reviews: 287,
    origin: 'Yamagata, Japan',
    description: 'Extra-crisp, honey-sweet apples with a satisfying snap. Japan\'s finest export variety.',
    organic: false,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    name: 'Sofia Restrepo',
    role: 'Owner',
    company: 'Finca Verde Organics',
    avatar: '',
    rating: 5,
    quote: 'FrescaMarket transformed my small farm into a real online business. Within two weeks of launching, I had orders from three different cities. The order management dashboard is incredibly easy to use and my sales doubled in the first month.',
    initials: 'SR',
    bgColor: 'from-green-400 to-emerald-500',
  },
  {
    id: 't2',
    name: 'Marco Villalobos',
    role: 'Head of Procurement',
    company: 'Sabores del Valle Restaurant Group',
    avatar: '',
    rating: 5,
    quote: 'We source fresh fruit for 7 restaurants across the city and FrescaMarket made our wholesale buying effortless. The bulk pricing tiers are transparent, delivery is always on time, and the quality is consistently exceptional.',
    initials: 'MV',
    bgColor: 'from-orange-400 to-amber-500',
  },
  {
    id: 't3',
    name: 'Camila Herrera',
    role: 'Founder',
    company: 'Juicery Box Subscription',
    avatar: '',
    rating: 5,
    quote: 'Building a juice subscription box requires a reliable fruit supplier who can guarantee quality. FrescaMarket\'s catalog management tools let me set recurring orders and the freshness guarantee means zero waste. My customers notice the difference.',
    initials: 'CH',
    bgColor: 'from-pink-400 to-rose-500',
  },
];

export const pricingTiers: PricingTier[] = [
  {
    id: 'starter',
    name: 'Starter',
    price: 0,
    period: 'month',
    description: 'Perfect for small vendors and individual farmers getting started online.',
    features: [
      { text: 'Up to 20 product listings', included: true },
      { text: 'Basic storefront page', included: true },
      { text: 'Order notifications via email', included: true },
      { text: 'Manual payment processing', included: true },
      { text: 'Sales analytics dashboard', included: false },
      { text: 'Custom domain', included: false },
      { text: 'Bulk order management', included: false },
    ],
    cta: 'Start Free',
    highlighted: false,
  },
  {
    id: 'grower',
    name: 'Grower',
    price: 29,
    period: 'month',
    description: 'For growing fruit businesses ready to scale sales and streamline operations.',
    features: [
      { text: 'Unlimited product listings', included: true },
      { text: 'Professional storefront + custom domain', included: true },
      { text: 'Automated order management', included: true },
      { text: 'Stripe & PayPal payments', included: true },
      { text: 'Full sales analytics dashboard', included: true },
      { text: 'Inventory alerts & restocking', included: true },
      { text: 'Bulk order management', included: false },
    ],
    cta: 'Start Growing',
    highlighted: true,
    badge: 'Most Popular',
  },
  {
    id: 'harvest',
    name: 'Harvest',
    price: 79,
    period: 'month',
    description: 'For large farms, distributors, and wholesale operations with high-volume needs.',
    features: [
      { text: 'Everything in Grower', included: true },
      { text: 'Wholesale pricing tiers', included: true },
      { text: 'Bulk order management', included: true },
      { text: 'Multi-location inventory', included: true },
      { text: 'API access & integrations', included: true },
      { text: 'Dedicated account manager', included: true },
      { text: 'White-label storefront', included: true },
    ],
    cta: 'Contact Sales',
    highlighted: false,
  },
];

export const faqs: FAQItem[] = [
  {
    id: 'f1',
    question: 'How quickly can I launch my fruit store online?',
    answer: 'Most sellers go live within 30 minutes. You create your account, add your products with photos and prices, set your delivery zones, and your storefront is ready to share. No technical skills required.',
  },
  {
    id: 'f2',
    question: 'What payment methods do customers use to pay me?',
    answer: 'FrescaMarket supports Stripe (all major credit/debit cards) and PayPal out of the box on the Grower plan and above. Starter plan sellers can enable manual bank transfer or cash-on-delivery options at no cost.',
  },
  {
    id: 'f3',
    question: 'Can I manage delivery and pickup options?',
    answer: 'Yes. You can configure home delivery with custom zones and fees, local pickup slots, or both. Customers choose at checkout. You receive instant notifications and can manage fulfillment from the dashboard.',
  },
  {
    id: 'f4',
    question: 'Is there a commission on my sales?',
    answer: 'FrescaMarket charges zero sales commission on all paid plans. You pay only the flat monthly subscription. On the free Starter plan there is a 3% platform fee per transaction, which disappears the moment you upgrade.',
  },
  {
    id: 'f5',
    question: 'How do I handle inventory for seasonal produce?',
    answer: 'Our inventory system supports both fixed stock counts and \"available when listed\" mode for seasonal items. You get low-stock alerts via email and can pause or hide listings with one click when an item is out of season.',
  },
  {
    id: 'f6',
    question: 'Can I offer wholesale pricing for bulk buyers?',
    answer: 'Absolutely. The Harvest plan includes tiered wholesale pricing where you set different price brackets by quantity. Restaurants, juice bars, and hotels frequently use this feature to place recurring large orders.',
  },
  {
    id: 'f7',
    question: 'What happens to my data if I cancel my subscription?',
    answer: 'Your data is always yours. If you cancel, you have 90 days to export your full product catalog, customer list, and order history as CSV files. We never delete your data within that window.',
  },
];

export const stats: Stat[] = [
  { id: 's1', label: 'Active Sellers', value: '3,800', suffix: '+', description: 'Farms and vendors online', emoji: '🧑‍🌾' },
  { id: 's2', label: 'Orders Delivered', value: '290K', suffix: '+', description: 'Fresh deliveries completed', emoji: '🚚' },
  { id: 's3', label: 'Customer Rating', value: '4.9', suffix: '★', description: 'Average buyer satisfaction', emoji: '🌟' },
  { id: 's4', label: 'Revenue Generated', value: '$8.4M', suffix: '', description: 'For our seller community', emoji: '💰' },
];

export const trustBrands: TrustBrand[] = [
  { id: 'b1', name: 'Whole Foods Co.', emoji: '🏪' },
  { id: 'b2', name: 'Verde Kitchen', emoji: '🥗' },
  { id: 'b3', name: 'Mercado Central', emoji: '🛒' },
  { id: 'b4', name: 'Sunrise Farms', emoji: '🌅' },
  { id: 'b5', name: 'Juicery Box', emoji: '🧣' },
  { id: 'b6', name: 'FreshRoute', emoji: '🚛' },
];

export const orders: Order[] = [
  { id: 'ORD-001', customer: 'Restaurante La Paloma', items: 'Alphonso Mangoes x5kg, Strawberries x3kg', total: 59.94, status: 'delivered', date: '2024-07-12', address: '14 Calle del Mar, Valencia' },
  { id: 'ORD-002', customer: 'Elena Morales', items: 'Dragon Fruit x4, Passion Fruit x6', total: 43.90, status: 'processing', date: '2024-07-14', address: '28 Av. Independencia, Barcelona' },
  { id: 'ORD-003', customer: 'Juice Studio BCN', items: 'Valencia Oranges x10kg, Blueberry Box x6', total: 79.84, status: 'pending', date: '2024-07-15', address: '3 Carrer de Balmes, Barcelona' },
  { id: 'ORD-004', customer: 'Andrea Castellanos', items: 'White Peaches x2kg, Fuji Apples x3kg', total: 25.45, status: 'delivered', date: '2024-07-11', address: '77 Gran Via, Madrid' },
  { id: 'ORD-005', customer: 'Hotel Botanico', items: 'Hass Avocados x10 pack, Pomegranates x8', total: 85.10, status: 'processing', date: '2024-07-15', address: '5 Paseo de la Reforma, CDMX' },
  { id: 'ORD-006', customer: 'Luca Fernandez', items: 'Yellow Watermelon x2, Coconuts x4', total: 41.94, status: 'cancelled', date: '2024-07-10', address: '12 Rambla Nova, Tarragona' },
];

export const sellers: Seller[] = [
  { id: 'sl1', name: 'Rosa Gutierrez', farm: 'Finca El Paraiso', location: 'Malaga, Spain', rating: 4.9, products: 18, sales: 1240, initials: 'RG', bgColor: 'from-green-400 to-emerald-500', certified: true, specialty: 'Tropical & Exotic', joined: 'March 2022' },
  { id: 'sl2', name: 'Tomas Okonkwo', farm: 'Tropic Sun Farms', location: 'Abidjan, Ivory Coast', rating: 4.8, products: 12, sales: 890, initials: 'TO', bgColor: 'from-yellow-400 to-orange-500', certified: true, specialty: 'Mangoes & Citrus', joined: 'June 2022' },
  { id: 'sl3', name: 'Mei Lin', farm: 'Dragon Valley Orchards', location: 'Guangdong, China', rating: 4.7, products: 9, sales: 540, initials: 'ML', bgColor: 'from-pink-400 to-rose-500', certified: false, specialty: 'Exotic & Dragon Fruit', joined: 'November 2022' },
  { id: 'sl4', name: 'Diego Montoya', farm: 'Sierra Verde Co.', location: 'Cundinamarca, Colombia', rating: 4.8, products: 22, sales: 1870, initials: 'DM', bgColor: 'from-teal-400 to-cyan-500', certified: true, specialty: 'Passion Fruit & Berries', joined: 'January 2022' },
  { id: 'sl5', name: 'Amara Diallo', farm: 'West Coast Harvest', location: 'Dakar, Senegal', rating: 4.6, products: 14, sales: 620, initials: 'AD', bgColor: 'from-purple-400 to-violet-500', certified: true, specialty: 'Baobab & Tropical', joined: 'August 2023' },
  { id: 'sl6', name: 'Pilar Ramos', farm: 'La Huerta de Pilar', location: 'Murcia, Spain', rating: 4.9, products: 30, sales: 2340, initials: 'PR', bgColor: 'from-red-400 to-pink-500', certified: true, specialty: 'Berries & Stone Fruits', joined: 'December 2021' },
];